---
- name: Playbook - Mise en place de Rsync
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Mise à niveau du système
      apt:
        upgrade: full
        force_apt_get: yes
        autoremove: yes

    - name: Installation de Rsync
      apt:
        name: rsync
        state: present

    - name: Montage automatique du disque au démarrage
      lineinfile:
        dest: /etc/fstab
        line: "/dev/sda1 /mnt/sda1/ exfat defaults,noatime 0 1"
        insertafter: EOF
        state: present

    - name: Ajout d'une tâche cron Rsync
      cron:
        minute: "0"
        hour: "*"
        user: "root"
        job: "sudo rsync -rvzu homepi@pi1.local:/mnt/sda1/ /mnt/sda1/"