---
- name: Playbook - Mise en place de Docker
  hosts: all
  become: yes
  tasks:
     - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Mise à niveau du système
      apt:
        upgrade: full
        force_apt_get: yes
        autoremove: yes

    - name: Ajout de la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Installation des paquets requis
      apt:
        name: "{{ item }}"
        state: present
      loop:
          - ca-certificates
          - curl

    - name: Création du répertoire /etc/apt/keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Téléchargement de la clé GPG de Docker
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Définition du repository de Docker
      blockinfile:
        path: /etc/apt/sources.list.d/docker.list
        block: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Mise à jour du cache Apt
      apt:
        update_cache: yes

    - name: Installation de Docker et des composants associés
      apt:
        name: "{{ item }}"
        state: present
      loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Vérification de l'installation de Docker
      command: docker run hello-world
      register: docker_hello
      ignore_errors: yes

    - name: Affichage du résultat de la vérification
      debug:
        msg: "Docker est correctement installé et fonctionnel."
      when: docker_hello is success

    - name: Cloner le dépôt Git
      git:
        repo: https://github.com/roccom14/HOMEpi
        dest: "/home/{{ ansible_user }}/HOMEpi"
        version: main
        force: yes
    
    - name: Création des clés SSL auto-signées
      shell: |
        COUNTRY="CH"
        STATE="Vaud"
        CITY="Lausanne"
        ORGANIZATION="EPFL"
        ORG_UNIT="ENAC-IT"
        COMMON_NAME="{{ ansible_user }}.local"
        EMAIL="rocco.ronzano@epfl.ch"

        sudo openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /home/{{ ansible_user }}/HOMEpi/docker/apache/server.key -out /home/{{ ansible_user }}/HOMEpi/docker/apache/server.crt -subj "/C=$COUNTRY/ST=$STATE/L=$CITY/O=$ORGANIZATION/OU=$ORG_UNIT/CN=$COMMON_NAME/emailAddress=$EMAIL"

    - name: Lancement du docker compose
      command: "docker compose -f /home/{{ ansible_user }}/HOMEpi/docker/docker-compose.yml up -d"